name: Ghost-generated pipeline

on:
  push:
    tags:
      - '*'

jobs:
  publish-extension:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install the dependencies
        run: npm i
  
      - name: Install vsce
        run: npm i -g vsce
      
      - name: Package
        run: vsce package
  
      - name: Publish
        run: vsce publish -p ${{ secrets.VSCE_PAT }}